image: nvidia/opengl

pipelines:
  custom:
    build-lib-build-main-run-main:
        - step:
            name: Build Lib Build Main Run Main
            script:
              - make && cd examples && ./main
