name: build
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-x86_64-gcc
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            libpazgraphics.a
            test/test.exe
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            libpazgraphics.a
            test/test
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install cmake xorg-dev xvfb
          curl -LO https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.zip
          unzip glfw-3.4.zip
          cd glfw-3.4
          cmake -S . -B build -D GLFW_BUILD_WAYLAND=0
          cd build
          make
          sudo make install
      - name: Simulate Display
        run: Xvfb &
      - name: Build and Test
        run: |
          export DISPLAY=:0
          make -j
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            libpazgraphics.a
            test/test
